# Generated by Django 4.2.5 on 2023-10-05 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("name",)},
        ),
    ]
